mesh: ???
prompt: ???
front_dir: "+z"

model_key: runwayml/stable-diffusion-v1-5
posi_prompt: "albedo, color, texture, high quality"
nega_prompt: "bad quality, low quality"
# control_mode: ['normal', ]
control_mode: ['normal', 'inpaint']
text_dir: false

wogui: false
vis: false
H: 800
W: 800
radius: 2
fovy: 60

outdir: logs
save_path: out.obj