### input
mesh: 
prompt: 
seed: "random"
### mesh's front-facing direction, check mesh.py for details
front_dir: "+z"

### output
outdir: logs
save_path: out.obj

### SD 1.5 checkpoint
model_key: runwayml/stable-diffusion-v1-5
# model_key: xyn-ai/anything-v4.0
# model_key: philz1337/revanimated

### additional positive/negative prompt
posi_prompt: ""
nega_prompt: ""

### controlnet model
control_mode: ['depth_inpaint']

### whether append 'front/side/back/top/bottom view' for the prompt, only use if the mesh's front dir is correctly set.
text_dir: false

### camera path to generate the texture
camera_path: default

### background image, default to white.
bg_image: None # assets/brick_wall.png

### generated texture image resolution
texture_size: 2048

### camera rendering resolution (choose from [512, 1024, 2048, 4096], larger than 512 will incur Real-ESRGAN super-resolution)
render_resolution: 1024

### open a gui for visualization (need a screen)
gui: false

### visualize intermediate results (support x11 forwarding)
vis: false

### recalculate uv coordinate for mesh
retex: false

### gui resolution
H: 800
W: 800

### camera setting
radius: 2.5
fovy: 50