mesh: ???
prompt: ???
front_dir: "+z"

# model_key: runwayml/stable-diffusion-v1-5
# model_key: xyn-ai/anything-v4.0
model_key: philz1337/revanimated
posi_prompt: "masterpiece, high quality"
nega_prompt: "bad quality, worst quality"
control_mode: ['depth_inpaint']
text_dir: true
bg_image: None # assets/brick_wall.png
texture_size: 2048
render_resolution: 512

gui: false
vis: false
H: 800
W: 800
radius: 2.5
fovy: 50

outdir: logs
save_path: out.obj