mesh: ???
prompt: ???
front_dir: "+z"

# model_key: runwayml/stable-diffusion-v1-5
# model_key: xyn-ai/anything-v4.0
model_key: philz1337/revanimated
posi_prompt: "masterpiece, high quality"
nega_prompt: "bad quality, worst quality, shadows"
control_mode: ['depth_inpaint']
text_dir: true
camera_path: front
bg_image: None # assets/brick_wall.png
texture_size: 1024
render_resolution: 1024

gui: false
vis: false
interactive: false
retex: false
H: 800
W: 800
radius: 2.5
fovy: 50

outdir: logs
save_path: out.obj